In [11]:
#index和columns的名字
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df =pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=range(1,51))
type(scores_df.index)
scores_df.index.name='學號'
scores_df.columns.name='科目'

In [16]:
#統計,依列加總
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
rank_series = sum_series.rank(method='min',ascending=False)
scores_df['總分']= sum_series
scores_df['平均']=mean_series
scores_df['排名']=rank_series
scores_df

科目   國文   英文  數學   地理  歷史     總分       平均    排名
學號
1    68   52  82   77  50  765.8   95.725  42.0
2    82   99  76   50  71  856.6  107.075  25.0
3    97   97  72  100  80  983.2  122.900   2.0
4    54   81  76   88  55  812.8  101.600  34.0
5    56   67  79   50  85  781.4   97.675  40.0
6    90   62  82   79  67  859.0  107.375  23.0
7    55   85  92   87  99  927.6  115.950   8.0
8    63   79  63   55  83  792.6   99.075  38.0
9    86   86  59   71  75  855.4  106.925  26.0
10   95   65  84   91  57  880.4  110.050  18.0
11   72   89  66   73  50  805.0  100.625  35.0
12   67   53  70   81  70  789.2   98.650  39.0
13   80   70  51   93  61  814.0  101.750  33.0
14   56   67  87   94  64  838.6  104.825  29.0
15   98   60  74   82  50  830.8  103.850  30.0
16   94   97  69   82  62  901.8  112.725  13.0
17   88   85  87   90  85  960.0  120.000   3.0
18   90   80  50   89  93  898.4  112.300  14.0
19   93   53  66   94  92  891.6  111.450  16.0
20   71   93  81   65  86  888.2  111.025  17.0
21  100   97  81   89  65  954.4  119.300   4.0
22   77   60  74   78  56  796.0   99.500  37.0
23   84   76  82   87  94  935.6  116.950   5.0
24   61   88  54   53  50  722.2   90.275  49.0
25   81   90  96   93  61  932.2  116.525   6.0
26   71   69  83   86  74  864.6  108.075  22.0
27   50   80  92  100  94  924.2  115.525   9.0
28   82   56  52   66  57  734.6   91.825  46.0
29   83   78  88   87  71  906.4  113.300  11.0
30   67   84  88   73  97  909.8  113.725  10.0
31   84   64  57   66  86  816.4  102.050  31.0
32   95   81  64   84  56  859.0  107.375  23.0
33   72   77  66   64  77  815.2  101.900  32.0
34   72   77  69   64  52  775.8   96.975  41.0
35   57   58  55   75  60  721.0   90.125  50.0
36   88   98  76   55  57  849.8  106.225  27.0
37   61  100  70   76  79  869.2  108.650  20.0
38   53   81  50   56  69  726.8   90.850  47.0
39   64   69  78   55  54  748.0   93.500  44.0
40   56   53  73   64  61  723.4   90.425  48.0
41   66   86  96   85  51  865.8  108.225  21.0
42   71   69  58   57  60  738.0   92.250  45.0
43   67   61  67   78  55  764.6   95.575  43.0
44   85   60  62   71  68  797.2   99.650  36.0
45   66   96  93   87  79  932.2  116.525   6.0
46   91   79  81   55  95  897.2  112.150  15.0
47   96   75  87   98  96  995.4  124.425   1.0
48   74   68  52   99  96  874.8  109.350  19.0
49   68   85  95   87  71  905.2  113.150  12.0
50   91   75  50   81  72  839.8  104.975  28.0

In [ ]:
#scores_df['排名'].sort_values(ascending =True)
#依排名排序
scores_sorted_df = scores_df.sort_values(by='排名',ascending =True)
scores_sorted_df

In [33]:
#班上前5名
#scores_first_five =scores_sorted_df[scores_sorted_df['排名']<=5]
scores_sorted_df.iloc[:5]

科目   國文  英文  數學   地理  歷史     總分       平均   排名
學號
47   96  75  87   98  96  995.4  124.425  1.0
3    97  97  72  100  80  983.2  122.900  2.0
17   88  85  87   90  85  960.0  120.000  3.0
21  100  97  81   89  65  954.4  119.300  4.0
23   84  76  82   87  94  935.6  116.950  5.0

In [34]:
#班上最後5名
scores_sorted_df.iloc[-5:]

科目  國文  英文  數學  地理  歷史     總分      平均    排名
學號
28  82  56  52  66  57  734.6  91.825  46.0
38  53  81  50  56  69  726.8  90.850  47.0
40  56  53  73  64  61  723.4  90.425  48.0
24  61  88  54  53  50  722.2  90.275  49.0
35  57  58  55  75  60  721.0  90.125  50.0