In [2]:
import requests
from requests import ConnectionError,HTTPError,Timeout
url = 'https://data.ntpc.gov.tw/api/datasets/010E5B15-3823-4B20-B401-B1CF000550C5/json?page=0&size=2000'
try:
    response = requests.get(url)    
    response.raise_for_status()    
except ConnectionError:
    print('找不到伺服器')
except HTTPError:
    print('網頁找不到')
except Timeout:
    print('超過時間沒有回應')
else:
    print('沒有發生問題')

import pandas as pd
df1 = pd.DataFrame(response.json(),
                   columns=['sna','tot','sbi','sarea','ar','bemp'])

df2 = df1.rename(columns={'sna':'站名', 'sarea':'區域', 'ar':'地址', 'tot':'數量','sbi':'可借', 'bemp':'可還'})

#object轉成int
df2['數量'] = df2['數量'].map(lambda value:int(value))
df2['可還'] = df2['可還'].map(lambda value:int(value))
df2['可借'] = df2['可借'].map(lambda value:int(value))

#使用'區域'欄位進行groupby及統計
groupby = df2.groupby(by='區域')
df3 = groupby[['數量','可還','可借']].sum()
df3

沒有發生問題

       數量    可還    可借
區域
三峽區  1482   859   608
三芝區   153    75    77
三重區  3592  2137  1412
中和區  3381  1871  1461
五股區   566   298   260
八里區   443   295   146
土城區  2737  1842   823
坪林區    65    34    29
新店區  2031  1218   782
板橋區  6983  4246  2699
林口區  2073  1179   863
永和區  1545  1037   497
汐止區  2353  1346  1003
泰山區   526   297   225
淡水區  1909  1028   870
深坑區   122    62    60
瑞芳區   204   143    61
石碇區    29    18    11
石門區    82    71    11
萬里區    99    77    21
金山區   163    95    68