In [12]:
import requests
from requests import ConnectionError,HTTPError,Timeout
url = 'https://data.ntpc.gov.tw/api/datasets/010E5B15-3823-4B20-B401-B1CF000550C5/json?page=0&size=2000'
try:
    response = requests.get(url)    
    response.raise_for_status()    
except ConnectionError:
    print('找不到伺服器')
except HTTPError:
    print('網頁找不到')
except Timeout:
    print('超過時間沒有回應')
else:
    print('沒有發生問題')

import pandas as pd
df1 = pd.DataFrame(response.json(),
                   columns=['sna','tot','sbi','sarea','ar','bemp'])

df2 = df1.rename(columns={'sna':'站名', 'sarea':'區域', 'ar':'地址', 'tot':'數量','sbi':'可借', 'bemp':'可還'})
df2

沒有發生問題

                        站名  數量  可借   區域                      地址  可還
0          YouBike2.0_下庄市場  20   4  八里區               舊城路21號(前)  16
1        YouBike2.0_八里行政中心  20   9  八里區    十三行路(靠中山路二段路口西南側人行道)  11
2    YouBike2.0_八里中庄市場綜合大樓  28   9  八里區    中山路一段268巷2號(對面汽車停車場)  19
3          YouBike2.0_大崁國小  20   5  八里區                忠八街2號(前)  15
4         YouBike2.0_龍形停車場  40  10  八里區        龍米路一段318號(對面停車場)  30
..                     ...  ..  ..  ...                     ...  ..
995        YouBike2.0_青潭國小  27   9  新店區                北宜路二段80號  18
996     YouBike2.0_中正路284巷  29  28  新店區           中正路284巷4弄3號南側   1
997      YouBike2.0_央北社會住宅  58   6  新店區        央北二路十四張口(西南側人行道)  52
998  YouBike2.0_中興路2段100巷口  21   6  新店區  五峰路63巷/中興路二段100巷口(天橋旁)  15
999      YouBike2.0_台北慈濟醫院  40   4  新店區              建國路289號旁空地  36

[1000 rows x 6 columns]

In [13]:
df2[['數量','可還','可借']] = df2[['數量','可還','可借']].astype(int)

In [18]:
df3 = df2[['數量','可還','可借']]
df3

     數量  可還  可借
0    20  16   4
1    20  11   9
2    28  19   9
3    20  15   5
4    40  30  10
..   ..  ..  ..
995  27  18   9
996  29   1  28
997  58  52   6
998  21  15   6
999  40  36   4

[1000 rows x 3 columns]

In [21]:
#使用'區域'欄位進行groupby及統計
groupby = df3.groupby(by='區域')
df4 = groupby.sum()
df4

       數量    可還    可借
區域
三峽區  1482   942   538
三芝區   153    61    44
三重區  3592  2294  1279
中和區  3381  2188  1171
五股區   566   352   211
八里區   443   305   138
土城區  2737  1749   948
坪林區    65     0     0
新店區  2031  1208   801
板橋區  6983  4728  2184
林口區  2073  1234   821
永和區  1545   984   556
汐止區  2353  1319  1009
泰山區   526   354   167
淡水區  1909  1193   712
深坑區   122    67    55
瑞芳區   204    76    38
石碇區    29     0     0
石門區    82     0     0
萬里區    99    22     6
金山區   163    81    54

In [ ]:
df4 = groupby[['數量','可還','可借']].sum()
df4