In [11]:
#index和columns的名字
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df =pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=range(1,51))
type(scores_df.index)
scores_df.index.name='學號'
scores_df.columns.name='科目'
scores_df

科目  國文  英文   數學   地理   歷史
學號
1   99  88   78   69   57
2   73  78   98   60   72
3   86  99   62   60   79
4   90  66   79   98  100
5   50  61   67   65   69
6   86  84   97   94   91
7   51  55   91   89   61
8   51  96   80   58   80
9   56  78   93   78   88
10  65  70   57   78   67
11  54  81   53   93  100
12  97  96   91   70   56
13  69  94   92   53   52
14  65  98   81   62   85
15  80  98   97   54   51
16  96  61   94   77  100
17  96  76   93   95   93
18  52  57   69   64   97
19  87  84   70   52   97
20  52  67   69   80   70
21  54  60   80   88   56
22  77  51   98   58   75
23  50  58   95  100   51
24  87  76   79   88   65
25  50  91   97   78   53
26  57  54   70   63   76
27  73  73   71   50  100
28  56  67   73   55   63
29  91  61   77   78  100
30  80  81   88   76   94
31  78  67   69   99   58
32  52  60   73   77   57
33  50  85   97   95   54
34  62  98   66   63   62
35  65  84   62   90   94
36  54  74   55   78   64
37  56  74   64   87   62
38  70  85   74   72   81
39  62  64   50   55   79
40  85  86   54   61  100
41  88  59   76   56   96
42  96  98   67   55   84
43  90  55   84   56   56
44  61  56   96   77  100
45  77  86  100   58   88
46  55  98  100   50   66
47  65  98   94   67   78
48  59  63   71   74   68
49  78  69   90   72   80
50  61  87   94   58   57

In [13]:
#將每一欄series計算統計後,再合併為dataframe
def call(s):
    min = s.min()
    max = s.max()
    median = s.median()
    return pd.Series([min,max,median],index=['最低分','最高分','中間值'])

scores_df.apply(call)

科目     國文    英文     數學     地理     歷史
最低分  50.0  51.0   50.0   50.0   51.0
最高分  99.0  99.0  100.0  100.0  100.0
中間值  65.0  76.0   79.0   71.0   75.5

In [ ]:
#列series,及格及不及格的數量
def call1(s):
    less60 = s[s<60]
    return less60.count()

less60_s = scores_df.apply(call1,axis=1)
scores_df['不及格的科目']=less60_s
scores_df